const tintColor = '#FF00FE';

export default {
	tabIconDefault: '#ccc',
	tabIconSelected: tintColor,
	userTag: '#7ABDED',
	tabBar: '#fefefe',
	errorBackground: 'red',
	errorText: '#fff',
	warningBackground: '#EAEB5E',
	warningText: '#666804',
	noticeBackground: tintColor,
	noticeText: '#fff',
	brightColor: '#2E313B',
	darkColor: '#1F2128',
	error: '#f70734',
	btnColor: '#606475',
	markerBright: '#53A8E3',
	markerDark: '#0D78C4',
	normalText: '#fbfbfb',
	fadedText: '#828796',
	insyte: '#FF00FE',
	success: '#2ecc71',
	border: '#ffffff66',
	toast: '#1C1C1C',
};
